services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: milkyway_app
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - CI_ENVIRONMENT=production
      - MYSQL_HOST=db
      - MYSQL_USER=milkyway_app
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=milky_way

  db:
    image: mysql:8.0
    container_name: milkyway_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: change_moi_aussi_root
      MYSQL_DATABASE: milky_way
      MYSQL_USER: milkyway_app
      MYSQL_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: